### ISSUE TITLE
Consul server and agents are not communicating because of firewall rules.

### ISSUE THREAD

**Issue by dalekurt** [hashicorp/terraform-google-vault#13]
I have a deployment with three (3) Consul servers and three (3) Vault servers running as consult clients. It seems as though there is no communication between Consult servers and client when I'm trying to unseal vault.

This is the output of `tail /opt/vault/log/vault-error.log`
```
2018/04/05 13:55:14.757133 [INFO ] core: stopping cluster listeners
2018/04/05 13:55:14.757509 [INFO ] core: shutting down forwarding rpc listeners
2018/04/05 13:55:14.758184 [INFO ] core: forwarding rpc listeners stopped
2018/04/05 13:55:15.220976 [INFO ] core: rpc listeners successfully shut down
2018/04/05 13:55:15.221474 [INFO ] core: cluster listeners successfully shut down
2018/04/05 13:55:15.221502 [INFO ] rollback: stopping rollback manager
2018/04/05 13:55:15.221761 [INFO ] core: pre-seal teardown complete
2018/04/05 13:57:41.082399 [INFO ] core: vault is unsealed
2018/04/05 13:57:41.083146 [INFO ] core: entering standby mode
2018/04/05 13:57:41.085157 [ERROR] core: failed to acquire lock: error=failed to create session: Unexpected response code: 500 (No known Consul servers)
```

On the Consult UI I'm only seeing the three (3) Sonsul Servers but no Agents
<img width="542" alt="screen shot 2018-04-05 at 10 01 41 am" src="https://user-images.githubusercontent.com/93077/38370592-79011d56-38b8-11e8-9cc4-386b8455fddb.png">

On investigating the consul-rule-cluster on GCP Firewall rules details I notice that the vault tags are not apart of the Targets or Source filters

<img width="570" alt="screen shot 2018-04-05 at 10 05 12 am" src="https://user-images.githubusercontent.com/93077/38370908-414c4902-38b9-11e8-9857-f9875be2c2e2.png">

After manually updating the Firewall rules to reflect the following:
<img width="445" alt="screen shot 2018-04-05 at 10 10 48 am" src="https://user-images.githubusercontent.com/93077/38371198-d64994b0-38b9-11e8-9230-3ed11e45be64.png">

Then on the Consul UI I now see that vault (consul agent) are communicating with the Consul Servers

<img width="527" alt="screen shot 2018-04-05 at 10 13 22 am" src="https://user-images.githubusercontent.com/93077/38371267-ff0f3fc6-38b9-11e8-8946-4c8c12942d74.png">

Am I the only one experiencing this?

**Comment by josh-padnick** [comment]
I just built the `vault-consul-image` from scratch and ran `terraform apply` on a fresh GCP project and everything works as expected.

**Comment by josh-padnick** [comment]
Closing this ticket due to inactivity, but feel free to re-open if this continues as an issue for you!

**Comment by chanux** [comment]
I have pretty much the same issue. I'm working with private cluster example, but using 
- terraform-google-vault -> tag v0.1.3
- terraform-google-consul -> tag v0.3.1
 
My `x-consul-rule-cluster` firewall rule did not have `x-vault` tag. So the Consul agents can't reach the Consul cluster. OP seem to have proper tags but checking the code, it is **not** added, at least in the version I use. Any help?

**Comment by josh-padnick** [comment]
@Etiene Can you take a look at this?

**Comment by StefanMadsen** [comment]
confirmed, this seems to be related to the fact that theres a single "cluster_tag_name" variable being exposed to the vault_cluster and consul_cluster modules.
If you've defined seperate cluster names in your private-cluster variables, (that is seperate vault <-> consul) clusters, then upon firewall creation, theres only a single variable, where there should be two
