### ISSUE TITLE
Subnetwork name can't be set, causing deploy failure

### ISSUE THREAD

**Issue by GNewbury1** [hashicorp/terraform-google-vault#22]
Our VPC network requires the use of a subnetwork with a name which isn't blank or `default`. As such, it is required for us to use a `subnetwork_name`, as can be used with `terraform-google-consul`.

I have completed the required change in pull request https://github.com/hashicorp/terraform-google-vault/pull/21

**Comment by josh-padnick** [comment]
Please see my comments in #21.
