### ISSUE TITLE
Consul no longer necessary?

### ISSUE THREAD

**Issue by carlodicelico** [hashicorp/terraform-google-vault#29]
It seems that since April, GCS supports Vault's HA model: https://cloud.google.com/blog/products/gcp/improving-the-google-cloud-storage-backend-for-hashicorp-vault. Also, since February, Cloud Spanner can be used, too: https://cloud.google.com/blog/products/gcp/announcing-google-cloud-spanner-as-a-vault-storage-backend. So, for new infrastructure on GCP, what's the benefit of using Consul?

**Comment by josh-padnick** [comment]
It's a fair point. The main motivations for using Consul as the Vault backend are:

- It's the only Vault backend officially supported by HashiCorp
- It enables Vault to run in High Availability (HA) mode
- At very high volumes of transactions, some users may find the eventually consistent nature of GCS (or e.g. Amazon) S3 to be insufficient and may want to leverage Consul for more "transactional" writes.

But honestly, for 95% of use cases, using GCS as a backend -- especially now that it supports HA -- should be fine.

**Comment by carlodicelico** [comment]
Thank you @josh-padnick—much appreciated.
