### ISSUE TITLE
GCS bucket name

### ISSUE THREAD

**Issue by Eoino** [hashicorp/terraform-google-vault#39]
There a reason that the `cluster_name` variable is used in favour of the aptly named `gcs_bucket_name` one?
https://github.com/hashicorp/terraform-google-vault/blob/70e8e8d8b6ca66e4dfe2ab875afa73de33955062/modules/vault-cluster/main.tf#L278

**Comment by robmorgan** [comment]
Hi @Eoino, it was likely just a typo. I'll make a small PR and see if the tests pass. `gcs_bucket_name` is a required parameter so users should be passing it in correctly.

**Comment by robmorgan** [comment]
@Etiene you might need to see if my PR passes the tests and then merge it if possible?

**Comment by sosimon** [comment]
https://github.com/hashicorp/terraform-google-vault/blob/master/modules/vault-cluster/main.tf#L299
and
https://github.com/hashicorp/terraform-google-vault/blob/master/modules/vault-cluster/main.tf#L312 should be fixed too I think.

**Comment by sosimon** [comment]
Sorry, has already been addressed in PR :)

**Comment by robmorgan** [comment]
@sosimon I'll make a release today.
