### ISSUE TITLE
Terraform plan failures - google firewall

### ISSUE THREAD

**Issue by aktarali** [hashicorp/terraform-google-vault#8]
Hi;

I am using 0.0.3 version and getting the following errors, can someone please help. Not sure why this is happening.

google aaktar$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.template_file.startup_script_nomad_client: Refreshing state...
data.template_file.startup_script_vault: Refreshing state...
data.template_file.startup_script_nomad_consul_server: Refreshing state...

------------------------------------------------------------------------

Error: Error running plan: 2 error(s) occurred:

* module.vault_cluster.output.firewall_rule_allow_inbound_health_check_id: Resource 'google_compute_firewall.allow_inboud_health_check' not found for variable 'google_compute_firewall.allow_inboud_health_check.id'
* module.vault_cluster.output.firewall_rule_allow_inbound_health_check_url: Resource 'google_compute_firewall.allow_inboud_health_check' not found for variable 'google_compute_firewall.allow_inboud_health_check.self_link'

Thanks
Ali.

**Comment by josh-padnick** [comment]
This is a Terraform 0.11.x compatibility issue. See https://github.com/hashicorp/terraform-google-vault/issues/6#issuecomment-347621870 for additional details.

Unfortunately Terraform 0.11.x had a backwards-incompatible change, and the discussion at https://github.com/hashicorp/terraform/issues/16726 is now resolved so we'll need to make this change, probably sometime next week.

It's a straightforward set of updates to the output values if anyone wants to open a PR for this! See #7 for a working example.

**Comment by josh-padnick** [comment]
Fixed by #7.
