### ISSUE TITLE
Remove nginx dependency

### ISSUE THREAD

**Issue by madmod** [hashicorp/terraform-google-vault#9]
GCP now supports HTTPS health checks so nginx is no longer needed. (See [GCE release notes](https://cloud.google.com/compute/docs/release-notes) _August 04, 2017_) I am willing to create a PR for this, but I would like someone to confirm that I'm not missing something.

**Comment by josh-padnick** [comment]
First, apologies for the delay responding on this. It appears you're correct! The limitation at the time we wrote this module wasn't the Google API support, it seems, but the Terraform provider support. However, it looks like Terraform's Google Provider now supports a [compute_https_health_check](https://www.terraform.io/docs/providers/google/r/compute_https_health_check.html). A PR to remove Nginx and use the HTTPS health check would be most welcome!

**Comment by madmod** [comment]
@josh-padnick I have implemented this enhancement in PR #16. It is a pretty big set of changes so I'd welcome another pair of eyes on it.

**Comment by josh-padnick** [comment]
Closing this issue due to #https://github.com/hashicorp/terraform-google-vault/pull/16#issuecomment-413720477. We're happy to reopen this if someone can show a working example.
